# Generated by Django 2.2.19 on 2023-10-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish',
        ),
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ManyToManyField(to='menu.Menu'),
        ),
    ]
